### ISSUE TITLE
Doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by GalaxyBound** [dmonad/nwfermi#1]
Changing `#include <asm/uaccess.h>` to `#include <linux/uaccess.h>` in nw-fermi.c allows this to compile, however it does not appear to be sending events.

**Comment by dmonad** [comment]
Hi @GalaxyBound 
I had this working with Ubuntu 16.04. But I won't continue this package as I gifted my touchscreen to a friend. 

But you should definitely try to keep it working. You could try to downgrade to an older kernel. 

Please let me know when you got it working. I'd be happy to receive a PR ;)
